// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr7slf44ebciRgeHyiLDkbnFTMg90IRXE',
    appId: '1:29745956691:web:d3661265770e0f456b03a6',
    messagingSenderId: '29745956691',
    projectId: 'contacts-53115',
    authDomain: 'contacts-53115.firebaseapp.com',
    storageBucket: 'contacts-53115.appspot.com',
    measurementId: 'G-LGD9G8KYP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtzVoBSx-f7Wj9BTv9F2Qfszti2enD0xU',
    appId: '1:29745956691:android:38b7924c199cea6a6b03a6',
    messagingSenderId: '29745956691',
    projectId: 'contacts-53115',
    storageBucket: 'contacts-53115.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA52S4CmjhfduZKgENbi2NbLmGQxPgQKeU',
    appId: '1:29745956691:ios:bf8d1820be6b85496b03a6',
    messagingSenderId: '29745956691',
    projectId: 'contacts-53115',
    storageBucket: 'contacts-53115.appspot.com',
    iosBundleId: 'com.example.contacts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA52S4CmjhfduZKgENbi2NbLmGQxPgQKeU',
    appId: '1:29745956691:ios:bf8d1820be6b85496b03a6',
    messagingSenderId: '29745956691',
    projectId: 'contacts-53115',
    storageBucket: 'contacts-53115.appspot.com',
    iosBundleId: 'com.example.contacts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr7slf44ebciRgeHyiLDkbnFTMg90IRXE',
    appId: '1:29745956691:web:3bcb294f8904ea796b03a6',
    messagingSenderId: '29745956691',
    projectId: 'contacts-53115',
    authDomain: 'contacts-53115.firebaseapp.com',
    storageBucket: 'contacts-53115.appspot.com',
    measurementId: 'G-ELJ1S9ENQ3',
  );

}